name: pr

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yaml
